### ISSUE TITLE
[Enhancement] add Windows support

### ISSUE THREAD

**Issue by OfirSiboni** [mehdiirh/LazyHelper#1]
Hey, great project!
I read your note about Windows support and I want to help.
As far as I can see, the Pythonic part will work for both Windows and Linux, so we can add Windows installation and background process creation in order to integrate your project with Windows without rewriting it.
What do you think?

**Comment by mehdiirh** [comment]
Hi !
Sure, I would appreciate that.
Also we need Windows commands for shutdown/reboot/lock etc.
